### ISSUE TITLE
报错 "WTF? 见鬼了？填完了但是没填？"

### ISSUE THREAD

**Issue by LomotHo** [b71db892/AutoCheckInUESTC#2]
```
[WARNING] WTF? 见鬼了？填完了但是没填？
[ERROR] Traceback (most recent call last):
  File "/app/server/main.py", line 16, in start
    obj.run()
  File "/app/server/driver.py", line 108, in run
    self.mobile_check_in_once()
  File "/app/server/driver.py", line 301, in mobile_check_in_once
    raise Exception('Unknown ERROR')
Exception: Unknown ERROR
```

**Comment by LomotHo** [comment]
第二次报这个

```
[INFO] DataBase 路径：/app/server/imgs.db                                                                                                                                                                                             [INFO] DataBase Tables:[('BLOCK_IMGS',), ('COOKED_IMGS',), ('RAW_IMGS',), ('sqlite_sequence',)]                                                                                                                                       [INFO] COOKED_IMGS exists.                                                                                                                                                                                                            [INFO] RAW_IMGS exists.                                                                                                                                                                                                               [INFO] BLOCK_IMGS exists.                                                                                                                                                                                                             chmod: cannot access '/app/server/chrome97_ubuntu64/chrome': No such file or directory                                                                                                                                                chmod: cannot access '/app/server/chrome97_ubuntu64/chrome_crashpad_handler': No such file or directory                                                                                                                               chmod: cannot access '/app/server/chrome97_ubuntu64/chromedriver': No such file or directory                                                                                                                                          [INFO] 找不到 chrome 二进制文件位置,使用系统默认位置                                                                                                                                                                                  [INFO] 找不到 chromedriver 二进制文件位置, 启用 undetected_chromedriver.                                                                                                                                                              [INFO] 初始化完成...                                                                                                                                                                                                                  [INFO] open website...
[INFO] input username ...
[INFO] input password ...
[INFO] login...
[INFO] Check Picture Test
[INFO] Calculate Picture Test.
[INFO] base_img is already ground truth.
[INFO] 实际距离191
[INFO] 减去半个滑块实际距离191
[INFO] last checkin text:每日报平安-**********
本人健康情况
正常
提报时间
2022-05-12 ******
[INFO] **********未打卡,最后签到时间:2022-05-12 ******
[INFO] 没填
[INFO] 新增签到记录
[ERROR] Traceback (most recent call last):
  File "/app/server/main.py", line 16, in start
    obj.run()
  File "/app/server/driver.py", line 108, in run
    self.mobile_check_in_once()
  File "/app/server/driver.py", line 268, in mobile_check_in_once
    self.driver.execute_script(js_comm)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 792, in execute_script
    'args': converted_args})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 400, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 236, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: headless chrome=101.0.4951.41)
Stacktrace:
#0 0x5602f3e32533 <unknown>
#1 0x5602f3b911e8 <unknown>
#2 0x5602f3b940a7 <unknown>
#3 0x5602f3b93f4b <unknown>
#4 0x5602f3b94ae2 <unknown>
#5 0x5602f3bf8e03 <unknown>
#6 0x5602f3be4f42 <unknown>
#7 0x5602f3bf8224 <unknown>
#8 0x5602f3be4e33 <unknown>
#9 0x5602f3bba71a <unknown>
#10 0x5602f3bbb875 <unknown>
#11 0x5602f3e76e1d <unknown>
#12 0x5602f3e7a751 <unknown>
#13 0x5602f3e6107e <unknown>
#14 0x5602f3e7b388 <unknown>
#15 0x5602f3e55fe0 <unknown>
#16 0x5602f3e97748 <unknown>
#17 0x5602f3e978c8 <unknown>
```

**Comment by b71db892** [comment]
这个😅，我也不太清楚原因。日志系统没做很详细，有时候加载慢的话会直接崩，Linux下如果显卡是计算卡也会崩。我是用了个win10的虚拟机挂着脚本，这一年只停过几次。后来把所有催打卡人的都屏蔽了，偶尔崩也不会被@，眼不见心不烦。
